[phases.setup]
aptPkgs = [
  "chromium",
  "chromium-driver",
  "fonts-liberation",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libcups2",
  "libdbus-1-3",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxrandr2",
  "libxrender1",
  "libxtst6",
  "libxkbcommon0",
  "libpango-1.0-0",
  "libcairo2"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python bdo_kr_bot.py"
